
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db
    username: root
    password: wkfskrk1!
  spring:
    mvc:
      view:
        prefix: /WEB-INF/views/
        suffix: .jsp
      jsp:
        enabled: true
      jstl:
        enabled: true
  mybatis:
    config-location: classpath:/mybatis-config.xml
    mapper-locations: classpath:/mapper/**/*.xml
    type-aliases-package: com.example.hr.domain.dto